### ISSUE TITLE
Typo in equation 17.6, section 17.1 page 517

### ISSUE THREAD

**Issue by charlielu05** [mikexcohen/LinAlgBook#10]
In the formula on page 517, when v.T@A@v is expanded.
We get `(ax+cy)x + (bx+dy)y` but then the following we end up with `ax^2 + (c+d)xy + dy^2`.
I think this should be `ax^2 + (b+c)xy + dy^2`

**Comment by mikexcohen** [comment]
Yep, that's a typo. Great catch! And thanks for letting me know. 

I've actually already caught that one, but it was probably in a newer version from what you got. (Don't worry, I haven't made any significant changes to the book since first publishing except for updating it to fix small typos like this.)
